import json
import random
import ssl
import time
from datetime import datetime, UTC

import paho.mqtt.client as mqtt


BROKER = "127.0.0.1"
PORT = 8883

TOPIC_TELEMETRY = "telemetry/drone/status"
TOPIC_COMMAND = "command/drone/status"
TOPIC_EVENT = "event/drone/status"


def telemetry_payload() -> dict:
    return {
        "@timestamp": datetime.now(UTC).isoformat(),
        "battery": {
            "level": random.randint(30, 100),
            "voltage": round(random.uniform(14.0, 16.8), 2),
        },
        "gps": {
            "lat": 55.75 + random.uniform(-0.001, 0.001),
            "lon": 37.61 + random.uniform(-0.001, 0.001),
            "sat": random.randint(8, 15),
        },
        "altitude": round(random.uniform(0, 120), 1),
        "speed": round(random.uniform(0, 15), 1),
        "yaw": random.uniform(-180, 180),
        "pitch": random.uniform(-90, 90),
        "roll": random.uniform(-90, 90),
        "flight_mode": random.choice(["LOITER", "AUTO", "RTL", "GUIDED"]),
        "armed": random.choice([True, False]),
        "rc": {"signal": random.randint(60, 100)},
        "temperature": random.randint(30, 70),
        "cpu_load": random.randint(5, 95),
    }


def command_payload() -> dict:
    return {
        "command": random.choice(["takeoff", "land", "rtl", "loiter", "emergency"]),
        "operator": random.choice(["user", "auto"]),
        "params": {
            "height": random.randint(5, 50),
            "speed": random.randint(1, 10),
        },
        "result": random.choice(["accepted", "rejected"]),
    }


def event_payload() -> dict:
    return {
        "event": random.choice(["gps_lost", "low_battery", "failsafe", "imu_error"]),
        "severity": random.choice(["low", "medium", "high"]),
        "duration": round(random.uniform(0.5, 5.0), 2),
        "message": "Autogenerated test event",
    }


def main() -> None:
    client = mqtt.Client()

    # правильный путь для запуска извне контейнера
    client.tls_set(
        ca_certs="mosquitto/conf/ca.crt",
        certfile="mosquitto/conf/client.crt",
        keyfile="mosquitto/conf/client.key",
        tls_version=ssl.PROTOCOL_TLS,
    )

    client.connect(BROKER, PORT, 60)

    while True:
        client.publish(TOPIC_TELEMETRY, json.dumps(telemetry_payload()))
        client.publish(TOPIC_COMMAND, json.dumps(command_payload()))
        client.publish(TOPIC_EVENT, json.dumps(event_payload()))
        print("Sent telemetry, command, event")
        time.sleep(2)


if __name__ == "__main__":
    main()
